<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace>ExcelDataProvider</RootNamespace>
    <AssemblyName>ExcelDataProvider</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\vMixController\bin\Debug\net472\DataProviders\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\vMixController\bin\Release\net472\DataProviders\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\vMixControllerDataProvider\vMixControllerDataProvider.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\vMixControllerSkin\vMixControllerSkin.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="FodyWeavers.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Costura.Fody">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ExcelDataReader" />
    <PackageReference Include="Extended.Wpf.Toolkit" />
    <PackageReference Include="Fody">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="System.Buffers" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Numerics.Vectors" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Text.Encodings.Web" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
    <PackageReference Include="System.ValueTuple" />
  </ItemGroup>
</Project>