<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>vMixStreamDeckLibrary</RootNamespace>
    <AssemblyName>vMixStreamDeckLibrary</AssemblyName>
    <ApplicationIcon>vMixStreamDeckLibrary.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.ServiceModel.Web" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources.resources" />
  </ItemGroup>
  <ItemGroup>
    <None Update="My\MySettings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>MySettings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="My\MySettings.Designer.cs">
      <DependentUpon>MySettings.settings</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WatsonWebsocket" />
  </ItemGroup>
</Project>